### ISSUE TITLE
Scan 했을 때 에러 발생

### ISSUE THREAD

**Issue by DevYu89** [zoyi/bingodb#31]
PUT으로 데이터를 하나 넣어둔 상태에서 Scan API를 사용 했을 때 에러가 발생합니다.

http://bingo.channel.io:4052/tables/onlines/scan?hash=7&limit=20&since=1234567890

[bingodb-1]2017-09-13T02:53:44.712779900Z 2017/09/13 02:53:44 0.712 #0000000100000001 - 172.17.0.10:80<->59.29.232.172:34870 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T02:53:47.471083168Z 2017/09/13 02:53:47 0.471 #0000000100000002 - 172.17.0.10:80<->59.29.232.172:34870 - PUT http://bingo.channel.io:4052/tables/onlines - PUT at /tables/onlines
[bingodb-1]2017-09-13T02:54:05.183941846Z 2017/09/13 02:54:05 1.184 #0000000100000003 - 172.17.0.10:80<->59.29.232.172:34870 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=7&limit=20&since=1234567890 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T02:54:05.186196328Z panic: interface conversion: interface {} is nil, not string
[bingodb-1]2017-09-13T02:54:05.186215811Z 
[bingodb-1]2017-09-13T02:54:05.186222041Z goroutine 51 [running]:
[bingodb-1]2017-09-13T02:54:05.186229447Z github.com/zoyi/bingodb/api.(*Resource).fetchIndex(0xc42000e0b8, 0xc4201e2480, 0xc4200648c0, 0x4)
[bingodb-1]2017-09-13T02:54:05.186238389Z 	/go/src/github.com/zoyi/bingodb/api/resource.go:151 +0x8b
[bingodb-1]2017-09-13T02:54:05.186244504Z github.com/zoyi/bingodb/api.(*Resource).Scan(0xc42000e0b8, 0xc4201e2480)
[bingodb-1]2017-09-13T02:54:05.186250316Z 	/go/src/github.com/zoyi/bingodb/api/resource.go:80 +0xa4
[bingodb-1]2017-09-13T02:54:05.186265796Z github.com/zoyi/bingodb/api.(*Resource).Scan-fm(0xc4201e2480)
[bingodb-1]2017-09-13T02:54:05.186270927Z 	/go/src/github.com/zoyi/bingodb/api/api.go:38 +0x34
[bingodb-1]2017-09-13T02:54:05.186275729Z github.com/zoyi/bingodb/api.cors.func1(0xc4201e2480)
[bingodb-1]2017-09-13T02:54:05.186280629Z 	/go/src/github.com/zoyi/bingodb/api/api.go:55 +0x12b
[bingodb-1]2017-09-13T02:54:05.186285382Z github.com/zoyi/bingodb/api.logging.func1(0xc4201e2480)
[bingodb-1]2017-09-13T02:54:05.186291985Z 	/go/src/github.com/zoyi/bingodb/api/api.go:62 +0x1aa
[bingodb-1]2017-09-13T02:54:05.186296840Z github.com/buaazp/fasthttprouter.(*Router).Handler(0xc420071a40, 0xc4201e2480)
[bingodb-1]2017-09-13T02:54:05.186301524Z 	/go/src/github.com/buaazp/fasthttprouter/router.go:300 +0x9d5
[bingodb-1]2017-09-13T02:54:05.186306155Z github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc4201e2480)
[bingodb-1]2017-09-13T02:54:05.186310837Z 	/go/src/github.com/zoyi/bingodb/cmd/bingodb/bingodb.go:25 +0x34
[bingodb-1]2017-09-13T02:54:05.186316173Z github.com/valyala/fasthttp.(*Server).serveConn(0xc4200e0500, 0x8d40c0, 0xc4201de000, 0x42a501, 0xc420030101)
[bingodb-1]2017-09-13T02:54:05.186321225Z 	/go/src/github.com/valyala/fasthttp/server.go:1555 +0x747
[bingodb-1]2017-09-13T02:54:05.186326295Z github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x8d40c0, 0xc4201de000, 0x1, 0x3)
[bingodb-1]2017-09-13T02:54:05.186331770Z 	/go/src/github.com/valyala/fasthttp/server.go:1269 +0x3e
[bingodb-1]2017-09-13T02:54:05.186356007Z github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc420124800, 0xc4201c2100)
[bingodb-1]2017-09-13T02:54:05.186362850Z 	/go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xdc
[bingodb-1]2017-09-13T02:54:05.186368143Z github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc420124800, 0xc4201c2100, 0x6c8f40, 0xc4201c2100)
[bingodb-1]2017-09-13T02:54:05.186372722Z 	/go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
[bingodb-1]2017-09-13T02:54:05.186375638Z created by github.com/valyala/fasthttp.(*workerPool).getCh
[bingodb-1]2017-09-13T02:54:05.186378567Z 	/go/src/github.com/valyala/fasthttp/workerpool.go:181 +0x13c

**Comment by siwonred** [comment]
https://github.com/zoyi/bingodb/commit/afcee69ad680f95f4d0b77e18be474feb355a82a 로 처리 했고 빌드 중
