### ISSUE TITLE
잘못된 SubIndex 값을 넣었을 때 에러 발생

### ISSUE THREAD

**Issue by DevYu89** [zoyi/bingodb#34]
잘못된 subindex 값을 url path에 넣었을 때 에러가 발생합니다.

아래는 로그입니다.

[bingodb-1]2017-09-13T06:08:31.260032006Z 2017/09/13 06:08:31 0.260 #0000000100000001 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:08:35.327767362Z 2017/09/13 06:08:35 0.328 #0000000100000002 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:08:36.899681300Z 2017/09/13 06:08:36 0.900 #0000000100000003 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:11:56.657077522Z 2017/09/13 06:11:56 0.657 #0000000100000004 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:11:57.439899678Z 2017/09/13 06:11:57 0.440 #0000000100000005 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:11:58.365067352Z 2017/09/13 06:11:58 0.365 #0000000100000006 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:12:22.194576289Z 2017/09/13 06:12:22 1.194 #0000000100000007 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/onlines - PUT at /tables/onlines
[bingodb-1]2017-09-13T06:12:26.262985342Z 2017/09/13 06:12:26 0.263 #0000000100000008 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:12:30.647219814Z 2017/09/13 06:12:30 0.647 #0000000100000009 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/indices/guest/scan?hash=8 - GET at /tables/onlines/indices/guest/scan
[bingodb-1]2017-09-13T06:12:55.484938055Z 2017/09/13 06:12:55 0.485 #000000010000000A - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:13:02.973997230Z 2017/09/13 06:13:02 0.974 #000000010000000B - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_1&sort=aa - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:13:06.841511970Z 2017/09/13 06:13:06 0.841 #000000010000000C - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_1 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:13:14.430477252Z 2017/09/13 06:13:14 0.430 #000000010000000D - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:13:15.439804270Z 2017/09/13 06:13:15 0.440 #000000010000000E - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:13:26.780393881Z 2017/09/13 06:13:26 0.780 #000000010000000F - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:13:29.551185732Z 2017/09/13 06:13:29 0.551 #0000000100000010 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:13:36.201073259Z 2017/09/13 06:13:36 1.201 #0000000100000011 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:15:28.463230712Z 2017/09/13 06:15:28 0.463 #0000000100000012 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_1 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:15:30.975577535Z 2017/09/13 06:15:30 0.975 #0000000100000013 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_2 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:16:24.635970213Z 2017/09/13 06:16:24 0.636 #0000000100000014 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:17:17.073303452Z 2017/09/13 06:17:17 1.073 #0000000100000015 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:19:36.535115848Z 2017/09/13 06:19:36 0.535 #0000000100000016 - 172.17.0.10:80<->59.29.232.172:36619 - DELETE http://bingo.channel.io:4052/tables/sockets?hash=socket_2 - DELETE at /tables/sockets
[bingodb-1]2017-09-13T06:19:38.805582459Z 2017/09/13 06:19:38 0.805 #0000000100000017 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:19:53.307716472Z 2017/09/13 06:19:53 1.308 #0000000100000018 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:19:53.965924591Z 2017/09/13 06:19:53 0.966 #0000000100000019 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:19:58.498314770Z 2017/09/13 06:19:58 0.498 #000000010000001A - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/onlines - PUT at /tables/onlines
[bingodb-1]2017-09-13T06:20:01.625303679Z 2017/09/13 06:20:01 0.625 #000000010000001B - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/onlines - PUT at /tables/onlines
[bingodb-1]2017-09-13T06:20:06.391272572Z 2017/09/13 06:20:06 0.391 #000000010000001C - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:20:23.509657967Z 2017/09/13 06:20:23 0.509 #000000010000001D - 172.17.0.10:80<->59.29.232.172:36619 - DELETE http://bingo.channel.io:4052/tables/onlines?hash=8 - DELETE at /tables/onlines
[bingodb-1]2017-09-13T06:20:26.409800668Z 2017/09/13 06:20:26 0.410 #000000010000001E - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:20:31.315115081Z 2017/09/13 06:20:31 1.315 #000000010000001F - 172.17.0.10:80<->59.29.232.172:36619 - DELETE http://bingo.channel.io:4052/tables/onlines?hash=8&sort=8%3AUser%3A121 - DELETE at /tables/onlines
[bingodb-1]2017-09-13T06:20:35.615783546Z 2017/09/13 06:20:35 0.616 #0000000100000020 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:20:48.188326860Z 2017/09/13 06:20:48 1.188 #0000000100000021 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:21:08.394793061Z 2017/09/13 06:21:08 0.395 #0000000100000022 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=socket_1 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:21:18.821531976Z 2017/09/13 06:21:18 0.821 #0000000100000023 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_2 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:21:21.551414474Z 2017/09/13 06:21:21 0.551 #0000000100000024 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_1 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:21:27.179111138Z 2017/09/13 06:21:27 1.179 #0000000100000025 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=socket_1 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:21:27.761696128Z 2017/09/13 06:21:27 0.762 #0000000100000026 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=socket_1 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:21:31.893475279Z 2017/09/13 06:21:31 0.893 #0000000100000027 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:21:34.416693492Z 2017/09/13 06:21:34 0.417 #0000000100000028 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables - GET at /tables
[bingodb-1]2017-09-13T06:21:40.491348033Z 2017/09/13 06:21:40 0.491 #0000000100000029 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:21:53.841204889Z 2017/09/13 06:21:53 0.841 #000000010000002A - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=socket_1&sort=1%3AUser%3A1388 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:21:57.738285416Z 2017/09/13 06:21:57 0.738 #000000010000002B - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=socket_1 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:23:59.313238812Z 2017/09/13 06:23:59 1.313 #000000010000002C - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:23:59.965390788Z 2017/09/13 06:23:59 0.965 #000000010000002D - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:24:13.966468510Z 2017/09/13 06:24:13 0.966 #000000010000002E - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/onlines - PUT at /tables/onlines
[bingodb-1]2017-09-13T06:24:20.106036941Z 2017/09/13 06:24:20 1.106 #000000010000002F - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:25:30.287554255Z 2017/09/13 06:25:30 1.287 #0000000100000030 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/onlines - PUT at /tables/onlines
[bingodb-1]2017-09-13T06:25:32.955662794Z 2017/09/13 06:25:32 0.955 #0000000100000031 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/onlines/scan?hash=8 - GET at /tables/onlines/scan
[bingodb-1]2017-09-13T06:40:03.551382272Z 2017/09/13 06:40:03 1.551 #0000000100000032 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:40:08.722671869Z 2017/09/13 06:40:08 0.723 #0000000100000033 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:40:14.094623096Z 2017/09/13 06:40:14 1.095 #0000000100000034 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:40:14.628009386Z 2017/09/13 06:40:14 0.628 #0000000100000035 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:40:28.261811143Z 2017/09/13 06:40:28 1.262 #0000000100000036 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:40:33.778198395Z 2017/09/13 06:40:33 0.778 #0000000100000037 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:40:37.227738184Z 2017/09/13 06:40:37 1.228 #0000000100000038 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:40:52.227988719Z 2017/09/13 06:40:52 1.228 #0000000100000039 - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:40:56.659736463Z 2017/09/13 06:40:56 0.660 #000000010000003A - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:42:03.050545456Z 2017/09/13 06:42:03 1.050 #000000010000003B - 172.17.0.10:80<->59.29.232.172:36619 - PUT http://bingo.channel.io:4052/tables/sockets - PUT at /tables/sockets
[bingodb-1]2017-09-13T06:42:09.127281307Z 2017/09/13 06:42:09 1.127 #000000010000003C - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:43:29.104994474Z 2017/09/13 06:43:29 1.105 #000000010000003D - 172.17.0.10:80<->59.29.232.172:36619 - DELETE http://bingo.channel.io:4052/tables/sockets?hash=socket_2 - DELETE at /tables/sockets
[bingodb-1]2017-09-13T06:43:34.569316554Z 2017/09/13 06:43:34 1.569 #000000010000003E - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/indices/person/scan
[bingodb-1]2017-09-13T06:43:45.259209961Z 2017/09/13 06:43:45 1.259 #000000010000003F - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/scan?hash=socket_5 - GET at /tables/sockets/scan
[bingodb-1]2017-09-13T06:44:08.733846921Z 2017/09/13 06:44:08 0.734 #0000000100000040 - 172.17.0.10:80<->59.29.232.172:36619 - GET http://bingo.channel.io:4052/tables/sockets/indices/person1/scan?hash=1%3AUser%3A1381 - GET at /tables/sockets/indices/person1/scan
[bingodb-1]2017-09-13T06:44:08.736061274Z panic: runtime error: invalid memory address or nil pointer dereference
[bingodb-1]2017-09-13T06:44:08.736077925Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x696717]
[bingodb-1]2017-09-13T06:44:08.736084835Z 
[bingodb-1]2017-09-13T06:44:08.736090113Z goroutine 120 [running]:
[bingodb-1]2017-09-13T06:44:08.736107213Z github.com/zoyi/bingodb.(*SubIndex).Scan(0x0, 0x6d85e0, 0xc4202de370, 0x6d39a0, 0xc420289980, 0x14, 0x3, 0x14, 0x0, 0x412d6c6f72746e6f, ...)
[bingodb-1]2017-09-13T06:44:08.736121202Z 	/go/src/github.com/zoyi/bingodb/index.go:111 +0x37
[bingodb-1]2017-09-13T06:44:08.736127384Z github.com/zoyi/bingodb/api.(*Resource).Scan(0xc42000e0b8, 0xc4203dc000)
[bingodb-1]2017-09-13T06:44:08.736133253Z 	/go/src/github.com/zoyi/bingodb/api/resource.go:82 +0x18c
[bingodb-1]2017-09-13T06:44:08.736147089Z github.com/zoyi/bingodb/api.(*Resource).Scan-fm(0xc4203dc000)
[bingodb-1]2017-09-13T06:44:08.736153986Z 	/go/src/github.com/zoyi/bingodb/api/api.go:38 +0x34
[bingodb-1]2017-09-13T06:44:08.736168769Z github.com/zoyi/bingodb/api.cors.func1(0xc4203dc000)
[bingodb-1]2017-09-13T06:44:08.736174108Z 	/go/src/github.com/zoyi/bingodb/api/api.go:55 +0x12b
[bingodb-1]2017-09-13T06:44:08.736179046Z github.com/zoyi/bingodb/api.logging.func1(0xc4203dc000)
[bingodb-1]2017-09-13T06:44:08.736183803Z 	/go/src/github.com/zoyi/bingodb/api/api.go:62 +0x1aa
[bingodb-1]2017-09-13T06:44:08.736193968Z github.com/buaazp/fasthttprouter.(*Router).Handler(0xc420071a40, 0xc4203dc000)
[bingodb-1]2017-09-13T06:44:08.736199092Z 	/go/src/github.com/buaazp/fasthttprouter/router.go:300 +0x9d5
[bingodb-1]2017-09-13T06:44:08.736203501Z github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc4203dc000)
[bingodb-1]2017-09-13T06:44:08.736209078Z 	/go/src/github.com/zoyi/bingodb/cmd/bingodb/bingodb.go:25 +0x34
[bingodb-1]2017-09-13T06:44:08.736218848Z github.com/valyala/fasthttp.(*Server).serveConn(0xc4200e0500, 0x8d40c0, 0xc42016e0e0, 0x42a501, 0xc400030101)
[bingodb-1]2017-09-13T06:44:08.736224015Z 	/go/src/github.com/valyala/fasthttp/server.go:1555 +0x747
[bingodb-1]2017-09-13T06:44:08.736232501Z github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x8d40c0, 0xc42016e0e0, 0x59b8cb01, 0x3acc5)
[bingodb-1]2017-09-13T06:44:08.736238257Z 	/go/src/github.com/valyala/fasthttp/server.go:1269 +0x3e
[bingodb-1]2017-09-13T06:44:08.736247442Z github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc420124800, 0xc4201bd1a0)
[bingodb-1]2017-09-13T06:44:08.736256897Z 	/go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xdc
[bingodb-1]2017-09-13T06:44:08.736265737Z github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc420124800, 0xc4201bd1a0, 0x6c8f40, 0xc4201bd1a0)
[bingodb-1]2017-09-13T06:44:08.736276384Z 	/go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
[bingodb-1]2017-09-13T06:44:08.736281348Z created by github.com/valyala/fasthttp.(*workerPool).getCh
[bingodb-1]2017-09-13T06:44:08.736290617Z 	/go/src/github.com/valyala/fasthttp/workerpool.go:181 +0x13c

**Comment by Terry-ZOYI** [comment]
Resolved in 1d5b1220a5edc05dc7fae61a92b37e69b533b45f
